export {
  chakraDocsApiTableSlotRecipe,
  chakraDocsArticleSlotRecipe,
  chakraDocsBadgeSlotRecipe,
  chakraDocsBreadcrumbsSlotRecipe,
  chakraDocsCalloutSlotRecipe,
  chakraDocsCardsSlotRecipe,
  chakraDocsCodeBlockSlotRecipe,
  chakraDocsFeedbackSlotRecipe,
  chakraDocsHeadingPermalinkSlotRecipe,
  chakraDocsLayoutSlotRecipe,
  chakraDocsMarkdownContentSlotRecipe,
  chakraDocsMobileNavigationSlotRecipe,
  chakraDocsMobileTableOfContentsSlotRecipe,
  chakraDocsPageActionsSlotRecipe,
  chakraDocsPaginationSlotRecipe,
  chakraDocsRecipeKeys,
  chakraDocsSearchSlotRecipe,
  chakraDocsSidebarSlotRecipe,
  chakraDocsSlotRecipes,
  chakraDocsStepsSlotRecipe,
  chakraDocsTableOfContentsSlotRecipe,
  chakraDocsTabsSlotRecipe,
  chakraDocsThemeConfig,
  chakraDocsVersionSelectSlotRecipe,
  type ChakraDocsRecipeKey,
  type ChakraDocsSlotRecipeConfig,
  type ChakraDocsThemeConfig,
  type ChakraDocsThemeStyleObject,
} from './theme/recipes.js';
