packages:
  - 'apps/*'
  - 'packages/*'

linkWorkspacePackages: true
preferWorkspacePackages: true
strictPeerDependencies: true
dedupePeerDependents: true

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  cypress: true
  esbuild: true
  nx: true

overrides:
  '@module-federation/dts-plugin>adm-zip': 0.6.1
  '@xhmikosr/decompress': ^11.1.4
  axios: ^1.20.0
  brace-expansion: ^5.0.12
  devalue: 5.9.3
  'minimatch@3>brace-expansion': ^2.1.7
  fast-uri: ^3.1.8
  http-cache-semantics: ^4.3.0
  js-yaml: ^4.3.2
  less: ^4.9.1
  nanoid: ^3.3.18
  'nx>smol-toml': 1.7.1
  'piscina@4': ^4.9.4
  postcss: ^8.5.24
  qs: ^6.16.0
  sharp: ^0.35.4
  supports-color: 8.1.1
  'svgo@3': ^3.3.5
  'svgo@4': ^4.1.0
  undici: ^7.29.1
  uuid: ^11.1.1

minimumReleaseAgeExclude:
  - http-cache-semantics@4.3.0

patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
