import { defineSlotRecipe } from '@chakra-ui/react';

export const siteOgImageRecipe = defineSlotRecipe({
  slots: [
    'stage',
    'root',
    'top',
    'brand',
    'eyebrow',
    'content',
    'title',
    'description',
    'bottom',
    'address',
    'credit',
    'wordmark',
  ],
  base: {
    stage: { bg: 'og.canvas', minW: '1200px', minH: '100svh' },
    root: {
      w: '1200px',
      h: '630px',
      p: 16,
      bg: 'og.canvas',
      color: 'og.foreground',
      flexDirection: 'column',
      justifyContent: 'space-between',
      overflow: 'hidden',
    },
    top: { alignItems: 'center', justifyContent: 'space-between', gap: 8 },
    brand: { fontSize: '2xl', fontWeight: 'medium', letterSpacing: 'tight' },
    eyebrow: { fontFamily: 'mono', fontSize: 'sm', color: 'og.muted' },
    content: { py: 8 },
    title: {
      fontSize: '88px',
      lineHeight: 1.05,
      maxW: '1000px',
      lineClamp: 2,
      overflowWrap: 'anywhere',
    },
    description: {
      mt: 6,
      fontSize: '28px',
      lineHeight: 1.4,
      maxW: '900px',
      color: 'og.muted',
      lineClamp: 2,
      overflowWrap: 'anywhere',
    },
    bottom: {
      pt: 6,
      borderTopWidth: '1px',
      borderColor: 'og.rule',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    address: { fontFamily: 'mono', fontSize: 'sm' },
    credit: {
      alignItems: 'center',
      gap: 3,
      fontSize: 'sm',
      color: 'og.muted',
    },
    wordmark: { w: '130px', h: '25px', objectFit: 'contain' },
  },
  variants: {
    density: {
      normal: { title: { fontSize: '88px' } },
      compact: { title: { fontSize: '64px', lineClamp: 3 } },
    },
  },
  defaultVariants: { density: 'normal' },
});
