import * as ChakraStyledSystemRuntime from '@chakra-ui/react/styled-system';
import type {
  ChakraDocsRecipeKey,
  ChakraDocsSlotRecipeConfig,
  ChakraDocsThemeConfig,
} from './theme-contract.js';

const { defineConfig, defineSlotRecipe } =
  ChakraStyledSystemRuntime as unknown as {
    defineConfig: <Config>(config: Config) => Config;
    defineSlotRecipe: <Recipe>(recipe: Recipe) => Recipe;
  };

export const chakraDocsRecipeKeys = {
  apiTable: 'chakraDocsApiTable',
  article: 'chakraDocsArticle',
  badge: 'chakraDocsBadge',
  breadcrumbs: 'chakraDocsBreadcrumbs',
  callout: 'chakraDocsCallout',
  cards: 'chakraDocsCards',
  codeBlock: 'chakraDocsCodeBlock',
  feedback: 'chakraDocsFeedback',
  layout: 'chakraDocsLayout',
  headingPermalink: 'chakraDocsHeadingPermalink',
  markdownContent: 'chakraDocsMarkdownContent',
  mobileNavigation: 'chakraDocsMobileNavigation',
  mobileTableOfContents: 'chakraDocsMobileTableOfContents',
  pageActions: 'chakraDocsPageActions',
  pagination: 'chakraDocsPagination',
  search: 'chakraDocsSearch',
  sidebar: 'chakraDocsSidebar',
  steps: 'chakraDocsSteps',
  tabs: 'chakraDocsTabs',
  tableOfContents: 'chakraDocsTableOfContents',
  versionSelect: 'chakraDocsVersionSelect',
} as const;

export const chakraDocsCardsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-cards',
  slots: ['root', 'card', 'icon', 'content', 'title', 'description', 'badge'],
  base: {
    root: {
      display: 'grid',
      gap: 4,
      gridTemplateColumns: { base: '1fr', md: 'repeat(2, minmax(0, 1fr))' },
      my: 6,
    },
    card: {
      alignItems: 'flex-start',
      bg: 'bg',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      color: 'fg',
      display: 'flex',
      gap: 3,
      p: 4,
      textDecoration: 'none',
      _hover: { bg: 'bg.subtle', textDecoration: 'none' },
    },
    icon: { color: 'fg.muted', flexShrink: 0, mt: 1 },
    content: { display: 'flex', flex: 1, flexDirection: 'column', gap: 1 },
    title: { color: 'fg', fontWeight: 'semibold' },
    description: { color: 'fg.muted', fontSize: 'sm' },
    badge: { ms: 2 },
  },
});

export const chakraDocsStepsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-steps',
  slots: ['root', 'item', 'indicator', 'content', 'title', 'description'],
  base: {
    root: {
      counterReset: 'chakra-docs-step',
      display: 'flex',
      flexDirection: 'column',
      gap: 6,
      listStyleType: 'none',
      my: 6,
      p: 0,
    },
    item: {
      alignItems: 'flex-start',
      counterIncrement: 'chakra-docs-step',
      display: 'flex',
      gap: 4,
    },
    indicator: {
      alignItems: 'center',
      bg: 'bg.subtle',
      borderColor: 'border',
      borderRadius: 'full',
      borderWidth: '1px',
      color: 'fg',
      display: 'inline-flex',
      flex: '0 0 auto',
      fontSize: 'sm',
      fontWeight: 'semibold',
      h: 8,
      justifyContent: 'center',
      w: 8,
      _before: { content: 'counter(chakra-docs-step)' },
    },
    content: { flex: 1, minW: 0 },
    title: { color: 'fg', fontWeight: 'semibold', mb: 1 },
    description: { color: 'fg.muted' },
  },
  variants: {
    customIndicator: {
      true: { indicator: { _before: { display: 'none' } } },
      false: {},
    },
  },
  defaultVariants: { customIndicator: false },
});

export const chakraDocsTabsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-tabs',
  slots: ['root', 'list', 'trigger', 'content'],
  base: {
    root: { my: 6 },
    list: {
      borderBottomColor: 'border',
      borderBottomWidth: '1px',
      display: 'flex',
      gap: 1,
      overflowX: 'auto',
    },
    trigger: {
      appearance: 'none',
      bg: 'transparent',
      borderColor: 'transparent',
      borderWidth: 0,
      borderBottomWidth: '2px',
      color: 'fg.muted',
      cursor: 'pointer',
      fontWeight: 'medium',
      mb: '-1px',
      px: 3,
      py: 2,
      whiteSpace: 'nowrap',
      _hover: { color: 'fg' },
      _focusVisible: { outline: '2px solid', outlineColor: 'fg' },
    },
    content: { color: 'fg', pt: 4 },
  },
  variants: {
    selected: {
      true: { trigger: { borderBottomColor: 'currentColor', color: 'fg' } },
      false: {},
    },
  },
  defaultVariants: { selected: false },
});

export const chakraDocsApiTableSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-api-table',
  slots: [
    'root',
    'table',
    'caption',
    'header',
    'row',
    'columnHeader',
    'cell',
    'name',
    'type',
    'defaultValue',
    'description',
    'required',
  ],
  base: {
    root: {
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      my: 6,
      minW: 0,
      maxW: 'full',
      w: 'full',
      overflowX: 'auto',
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'border.emphasized',
        outlineOffset: '2px',
      },
    },
    table: { borderCollapse: 'collapse', textAlign: 'start', w: 'full' },
    caption: { color: 'fg.muted', fontSize: 'sm', p: 3, textAlign: 'start' },
    header: { bg: 'bg.subtle' },
    row: { borderBottomColor: 'border', borderBottomWidth: '1px' },
    columnHeader: {
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      px: 3,
      py: 2,
      textAlign: 'start',
    },
    cell: { color: 'fg', fontSize: 'sm', px: 3, py: 3, verticalAlign: 'top' },
    name: { fontWeight: 'semibold' },
    type: { color: 'fg.muted', fontFamily: 'mono', fontSize: 'xs' },
    defaultValue: { color: 'fg.muted', fontFamily: 'mono', fontSize: 'xs' },
    description: { color: 'fg.muted' },
    required: { ms: 2 },
  },
});

export const chakraDocsBadgeSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-badge',
  slots: ['root'],
  base: {
    root: {
      bg: 'bg.subtle',
      borderColor: 'border',
      borderRadius: 'sm',
      borderWidth: '1px',
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      px: 1.5,
      py: 0.5,
    },
  },
  variants: {
    tone: {
      neutral: {},
      accent: { root: { bg: 'bg.emphasized', color: 'fg' } },
    },
  },
  defaultVariants: { tone: 'neutral' },
});

export const chakraDocsLayoutSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-layout',
  slots: ['root', 'mobileNavigation', 'inner', 'sidebar', 'content'],
  base: {
    root: {
      maxW: '7xl',
      minW: 0,
      px: { base: 4, md: 8 },
      py: 8,
    },
    mobileNavigation: { mb: { base: 6, lg: 0 } },
    inner: {
      alignItems: 'flex-start',
      display: 'flex',
      flexDirection: { base: 'column', lg: 'row' },
      gap: { base: 8, lg: 12 },
    },
    sidebar: { display: { base: 'none', lg: 'block' } },
    content: {
      flex: '1',
      minW: 0,
      maxW: 'full',
      w: 'full',
    },
  },
});

export const chakraDocsMobileNavigationSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-mobile-navigation',
  slots: [
    'root',
    'trigger',
    'triggerIcon',
    'triggerLabel',
    'backdrop',
    'positioner',
    'content',
    'header',
    'title',
    'closeTrigger',
    'search',
    'body',
    'sidebar',
  ],
  base: {
    root: { display: { base: 'block', lg: 'none' } },
    trigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      color: 'fg',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: 'sm',
      fontWeight: 'medium',
      gap: 2,
      minH: 9,
      px: 3,
      _hover: { bg: 'bg.subtle' },
      _focusVisible: { outline: '2px solid', outlineColor: 'fg' },
    },
    triggerIcon: { display: 'inline-flex', flexShrink: 0 },
    triggerLabel: { display: 'inline-flex' },
    backdrop: { bg: 'bg.inverted/40', display: { base: 'block', lg: 'none' } },
    positioner: {
      alignItems: 'stretch',
      display: { base: 'flex', lg: 'none' },
      justifyContent: 'flex-start',
    },
    content: {
      bg: 'bg.panel',
      borderColor: 'border',
      borderEndWidth: '1px',
      borderRadius: 0,
      boxShadow: 'xl',
      color: 'fg',
      display: 'flex',
      flexDirection: 'column',
      h: '100dvh',
      maxH: '100dvh',
      maxW: 'min(22rem, calc(100vw - 2rem))',
      w: 'full',
    },
    header: {
      alignItems: 'center',
      borderBottomColor: 'border',
      borderBottomWidth: '1px',
      display: 'flex',
      flexShrink: 0,
      justifyContent: 'space-between',
      minH: 14,
      px: 4,
    },
    title: { color: 'fg', fontSize: 'sm', fontWeight: 'semibold' },
    closeTrigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderRadius: 'md',
      borderWidth: 0,
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: 'lg',
      h: 8,
      justifyContent: 'center',
      w: 8,
      _hover: { bg: 'bg.subtle', color: 'fg' },
      _focusVisible: { outline: '2px solid', outlineColor: 'fg' },
    },
    search: {
      borderBottomColor: 'border',
      borderBottomWidth: '1px',
      flexShrink: 0,
      p: 3,
    },
    body: { flex: 1, minH: 0, overflowY: 'auto', p: 4 },
    sidebar: {
      flex: 'none',
      position: 'static',
      top: 'auto',
      w: 'full',
    },
  },
});

export const chakraDocsArticleSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-article',
  slots: [
    'root',
    'header',
    'breadcrumbs',
    'heading',
    'title',
    'description',
    'actions',
  ],
  base: {
    root: {
      maxW: '3xl',
      minW: 0,
      w: 'full',
      // Custom Markdown renderers may emit bare tables. Contain those locally;
      // tables with an external scroll area keep their native table layout.
      '& :where(table:not([data-chakra-docs-table-scroll="external"]))': {
        display: 'block',
        maxW: 'full',
        overflowX: 'auto',
        w: 'full',
      },
    },
    header: { mb: 8 },
    breadcrumbs: { mb: 4 },
    heading: {
      alignItems: 'flex-start',
      display: 'flex',
      flexWrap: 'wrap',
      gap: 4,
      justifyContent: 'space-between',
    },
    title: { mb: 3 },
    description: { color: 'fg.muted', fontSize: 'lg' },
    actions: { flexShrink: 0 },
  },
});

export const chakraDocsBreadcrumbsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-breadcrumbs',
  slots: ['root', 'list', 'item', 'link', 'current', 'separator'],
  base: {
    root: { color: 'fg.muted', fontSize: 'sm' },
    list: {
      alignItems: 'center',
      display: 'flex',
      flexWrap: 'wrap',
      gap: 2,
      listStyleType: 'none',
      m: 0,
      p: 0,
    },
    item: { alignItems: 'center', display: 'inline-flex', gap: 2 },
    link: {
      color: 'fg.muted',
      textDecoration: 'none',
      _hover: { color: 'fg', textDecoration: 'underline' },
    },
    current: { color: 'fg', fontWeight: 'medium' },
    separator: { color: 'fg.subtle', userSelect: 'none' },
  },
});

export const chakraDocsHeadingPermalinkSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-heading-permalink',
  slots: ['root', 'trigger', 'indicator'],
  base: {
    root: { display: 'inline-flex' },
    trigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderWidth: 0,
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'inline-flex',
      font: 'inherit',
      fontSize: '0.75em',
      ms: 2,
      opacity: 0.5,
      p: 0,
      _hover: { color: 'fg', opacity: 1 },
      _focusVisible: { outline: '2px solid', outlineColor: 'fg' },
    },
    indicator: { display: 'inline-flex' },
  },
});

export const chakraDocsFeedbackSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-feedback',
  slots: [
    'root',
    'prompt',
    'choices',
    'option',
    'comment',
    'actions',
    'submit',
    'status',
  ],
  base: {
    root: {
      borderTopWidth: '1px',
      display: 'flex',
      flexDirection: 'column',
      gap: 3,
      mt: 10,
      pt: 6,
    },
    prompt: { color: 'fg', fontSize: 'sm', fontWeight: 'semibold' },
    choices: { display: 'flex', flexWrap: 'wrap', gap: 2 },
    option: {
      bg: 'bg',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      color: 'fg',
      fontSize: 'sm',
      minH: 8,
      px: 3,
      _hover: { bg: 'bg.subtle' },
    },
    comment: {
      bg: 'bg',
      borderColor: 'border',
      color: 'fg',
      fontSize: 'sm',
      minH: 24,
      resize: 'vertical',
    },
    actions: { display: 'flex', justifyContent: 'flex-end' },
    submit: { minH: 8 },
    status: { color: 'fg.muted', fontSize: 'sm' },
  },
  variants: {
    selected: {
      true: {
        option: {
          bg: 'fg',
          borderColor: 'fg',
          color: 'bg',
          _hover: { bg: 'fg' },
        },
      },
      false: {},
    },
    status: {
      idle: {},
      submitting: { status: { color: 'fg.muted' } },
      submitted: { status: { color: 'fg.success' } },
      error: { status: { color: 'fg.error' } },
    },
  },
  defaultVariants: { selected: false, status: 'idle' },
});

export const chakraDocsPageActionsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-page-actions',
  slots: [
    'root',
    'copyRoot',
    'trigger',
    'primaryTrigger',
    'icon',
    'label',
    'indicator',
    'menu',
    'menuTrigger',
    'menuIndicator',
    'menuPositioner',
    'menuContent',
    'menuItem',
    'menuGroup',
    'menuGroupLabel',
    'menuSeparator',
    'submenu',
    'submenuTrigger',
    'submenuIndicator',
    'submenuPositioner',
    'submenuContent',
    'description',
  ],
  base: {
    root: {
      '--chakra-docs-page-actions-font-size': 'fontSizes.sm',
      '--chakra-docs-page-actions-gap': 'spacing.2',
      '--chakra-docs-page-actions-height': 'sizes.8',
      '--chakra-docs-page-actions-menu-padding': 'spacing.2',
      '--chakra-docs-page-actions-radius': 'radii.md',
      '--chakra-docs-page-actions-trigger-padding': 'spacing.3',
      alignItems: 'center',
      display: 'flex',
      flexWrap: 'wrap',
      gap: 2,
    },
    copyRoot: { display: 'contents' },
    trigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderColor: 'border',
      borderStyle: 'solid',
      borderWidth: '1px',
      color: 'fg',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: 'var(--chakra-docs-page-actions-font-size)',
      fontWeight: 'medium',
      gap: 'var(--chakra-docs-page-actions-gap)',
      justifyContent: 'center',
      lineHeight: 'short',
      minH: 'var(--chakra-docs-page-actions-height)',
      position: 'relative',
      px: 'var(--chakra-docs-page-actions-trigger-padding)',
      py: 1,
      textDecoration: 'none',
      borderRadius: 'var(--chakra-docs-page-actions-radius)',
      _hover: { bg: 'bg.subtle', textDecoration: 'none' },
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'fg',
        outlineOffset: '2px',
        zIndex: 1,
      },
      _disabled: {
        cursor: 'not-allowed',
        opacity: 0.5,
        _hover: { bg: 'transparent' },
      },
    },
    primaryTrigger: {},
    icon: { display: 'inline-flex', flexShrink: 0 },
    label: { display: 'inline-flex' },
    indicator: { display: 'inline-flex' },
    menu: { display: 'inline-flex' },
    menuTrigger: {
      cursor: 'pointer',
      listStyle: 'none',
      _marker: { display: 'none' },
    },
    menuIndicator: {
      display: 'inline-flex',
      flexShrink: 0,
      transition: 'transform 150ms ease',
      _open: { transform: 'rotate(180deg)' },
    },
    menuPositioner: { zIndex: 'dropdown' },
    menuContent: {
      bg: 'bg',
      color: 'fg',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      boxShadow: 'md',
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      minW: '15rem',
      p: 1,
    },
    menuItem: {
      alignItems: 'flex-start',
      appearance: 'none',
      bg: 'transparent',
      borderRadius: 'sm',
      borderWidth: 0,
      color: 'fg',
      cursor: 'pointer',
      display: 'flex',
      fontSize: 'var(--chakra-docs-page-actions-font-size)',
      gap: 3,
      p: 2,
      textAlign: 'start',
      textDecoration: 'none',
      w: 'full',
      _hover: { bg: 'bg.subtle', textDecoration: 'none' },
      _highlighted: { bg: 'bg.subtle', color: 'fg' },
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'fg',
        outlineOffset: '-2px',
      },
      _disabled: { cursor: 'not-allowed', opacity: 0.5 },
    },
    menuGroup: { display: 'flex', flexDirection: 'column', gap: 1 },
    menuGroupLabel: {
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      px: 2,
      py: 1,
    },
    menuSeparator: {
      borderColor: 'border',
      borderStyle: 'solid',
      borderWidth: 0,
      borderTopWidth: '1px',
      m: 1,
    },
    submenu: { display: 'contents' },
    submenuTrigger: {
      cursor: 'pointer',
      listStyle: 'none',
      _marker: { display: 'none' },
    },
    submenuIndicator: {
      display: 'inline-flex',
      flexShrink: 0,
      marginInlineStart: 'auto',
      transition: 'transform 150ms ease',
    },
    submenuPositioner: { zIndex: 'dropdown' },
    submenuContent: {
      bg: 'bg',
      color: 'fg',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      boxShadow: 'md',
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
      minW: '15rem',
      p: 1,
    },
    description: { color: 'fg.muted', fontSize: 'xs' },
  },
  variants: {
    size: {
      sm: {
        root: {
          '--chakra-docs-page-actions-font-size': 'fontSizes.xs',
          '--chakra-docs-page-actions-gap': 'spacing.1.5',
          '--chakra-docs-page-actions-height': 'sizes.7',
          '--chakra-docs-page-actions-menu-padding': 'spacing.2',
          '--chakra-docs-page-actions-radius': 'radii.sm',
          '--chakra-docs-page-actions-trigger-padding': 'spacing.2',
        },
      },
      md: {},
      lg: {
        root: {
          '--chakra-docs-page-actions-font-size': 'fontSizes.md',
          '--chakra-docs-page-actions-height': 'sizes.10',
          '--chakra-docs-page-actions-menu-padding': 'spacing.3',
          '--chakra-docs-page-actions-radius': 'radii.lg',
          '--chakra-docs-page-actions-trigger-padding': 'spacing.4',
        },
      },
    },
    variant: {
      default: {},
      split: {
        root: { alignItems: 'stretch', flexWrap: 'nowrap', gap: 0 },
        primaryTrigger: {
          borderEndWidth: 0,
          borderEndRadius: 0,
        },
        menu: { marginInlineStart: 0 },
        menuTrigger: {
          borderStartRadius: 0,
          px: 'var(--chakra-docs-page-actions-menu-padding)',
        },
      },
    },
  },
  defaultVariants: { size: 'md', variant: 'default' },
});

export const chakraDocsSidebarSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-sidebar',
  slots: [
    'root',
    'list',
    'item',
    'link',
    'sectionTitle',
    'badge',
    'children',
    'trigger',
    'indicator',
    'content',
  ],
  base: {
    root: {
      flex: '0 0 16rem',
      position: { lg: 'sticky' },
      w: { base: '100%', lg: '16rem' },
    },
    list: { listStyleType: 'none', m: 0, ps: 0 },
    item: { py: 1 },
    sectionTitle: { fontWeight: 'semibold' },
    badge: { ms: 2 },
    children: { mt: 1, ps: 4 },
    trigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderWidth: 0,
      color: 'inherit',
      cursor: 'pointer',
      display: 'inline-flex',
      font: 'inherit',
      fontWeight: 'semibold',
      gap: 2,
      justifyContent: 'space-between',
      p: 0,
      textAlign: 'start',
      w: 'full',
    },
    indicator: {
      display: 'inline-flex',
      flex: '0 0 auto',
      transition: 'transform 150ms ease',
    },
    content: {},
  },
  variants: {
    active: {
      true: {
        link: {
          color: 'fg',
          fontWeight: 'semibold',
        },
      },
      false: {},
    },
    expanded: {
      true: {
        indicator: { transform: 'rotate(90deg)' },
        content: { display: 'block' },
      },
      false: {
        indicator: { transform: 'rotate(0deg)' },
        content: { display: 'none' },
      },
    },
    linked: {
      true: { trigger: { ms: 2, w: 'auto' } },
      false: {},
    },
  },
  defaultVariants: { active: false, expanded: true, linked: false },
});

export const chakraDocsTableOfContentsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-table-of-contents',
  slots: ['root', 'label', 'list', 'item', 'link', 'activeIndicator'],
  base: {
    root: {
      display: { base: 'none', xl: 'block' },
      flex: '0 0 14rem',
      position: 'sticky',
    },
    label: { fontWeight: 'semibold', mb: 3 },
    list: { listStyleType: 'none', m: 0, ps: 0 },
    item: { py: 1 },
    link: {
      color: 'fg.muted',
      display: 'block',
      fontSize: 'sm',
      fontWeight: 'medium',
      position: 'relative',
      px: 2,
      py: 1,
      _hover: {
        color: 'fg',
        textDecoration: 'none',
      },
    },
    activeIndicator: {
      bg: 'transparent',
      insetBlock: 0,
      insetInlineStart: 0,
      position: 'absolute',
      w: '2px',
    },
  },
  variants: {
    active: {
      true: {
        link: {
          color: 'fg',
          _hover: { color: 'fg' },
        },
        activeIndicator: { bg: 'currentColor' },
      },
      false: {},
    },
  },
  defaultVariants: { active: false },
});

export const chakraDocsMobileTableOfContentsSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-mobile-table-of-contents',
  slots: [
    'root',
    'trigger',
    'triggerLabel',
    'current',
    'indicator',
    'content',
    'list',
    'item',
    'link',
    'activeIndicator',
  ],
  base: {
    root: {
      borderBottomWidth: '1px',
      display: { base: 'block', xl: 'none' },
      mb: 6,
      pb: 3,
    },
    trigger: {
      alignItems: 'center',
      cursor: 'pointer',
      display: 'flex',
      fontSize: 'sm',
      fontWeight: 'semibold',
      gap: 2,
      justifyContent: 'space-between',
      listStyle: 'none',
      _marker: { display: 'none' },
    },
    triggerLabel: { color: 'fg' },
    current: {
      color: 'fg.muted',
      fontWeight: 'normal',
      marginInlineStart: 'auto',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    indicator: { color: 'fg.muted', flexShrink: 0 },
    content: { pt: 3 },
    list: { listStyleType: 'none', m: 0, p: 0 },
    item: { py: 1 },
    link: {
      color: 'fg.muted',
      display: 'block',
      fontSize: 'sm',
      position: 'relative',
      px: 2,
      py: 1,
      textDecoration: 'none',
      _hover: { color: 'fg', textDecoration: 'none' },
    },
    activeIndicator: {
      bg: 'transparent',
      insetBlock: 0,
      insetInlineStart: 0,
      position: 'absolute',
      w: '2px',
    },
  },
  variants: {
    active: {
      true: {
        link: { color: 'fg', fontWeight: 'semibold' },
        activeIndicator: { bg: 'currentColor' },
      },
      false: {},
    },
  },
  defaultVariants: { active: false },
});

export const chakraDocsSearchSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-search',
  slots: [
    'trigger',
    'triggerLabel',
    'shortcut',
    'backdrop',
    'positioner',
    'root',
    'header',
    'title',
    'body',
    'input',
    'results',
    'sectionLabel',
    'resultList',
    'result',
    'resultLink',
    'resultRow',
    'resultContent',
    'resultTitle',
    'resultDescription',
    'resultBadge',
    'status',
  ],
  base: {
    trigger: {
      justifyContent: 'space-between',
      minW: { base: 'full', md: '13rem' },
    },
    triggerLabel: { color: 'fg.muted', fontWeight: 'medium' },
    positioner: {
      '--chakra-docs-search-offset': { base: '3rem', md: '5rem' },
      px: 4,
      pt: 'var(--chakra-docs-search-offset)',
      pb: 4,
    },
    root: {
      display: 'flex',
      flexDirection: 'column',
      maxH: 'calc(100dvh - var(--chakra-docs-search-offset) - 1rem)',
      maxW: '2xl',
      my: 0,
      overflow: 'hidden',
      p: 0,
    },
    header: { borderBottomWidth: '1px', flexShrink: 0, p: 4 },
    title: { fontSize: 'sm' },
    body: { display: 'flex', flexDirection: 'column', minH: 0, p: 0 },
    input: {
      borderRadius: 0,
      borderWidth: 0,
      fontSize: 'lg',
      flexShrink: 0,
      h: 14,
      _focus: { boxShadow: 'none' },
    },
    results: {
      borderTopWidth: '1px',
      maxH: '420px',
      minH: 0,
      overscrollBehavior: 'contain',
      overflowY: 'auto',
      p: 3,
    },
    sectionLabel: {
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      px: 2,
      py: 1,
    },
    resultList: { gap: 1 },
    result: {
      bg: 'transparent',
      borderColor: 'transparent',
      borderRadius: 'md',
      borderWidth: '1px',
      display: 'block',
      p: 3,
      _hover: { bg: 'bg.subtle', textDecoration: 'none' },
    },
    resultRow: {
      alignItems: 'flex-start',
      justifyContent: 'space-between',
    },
    resultContent: { gap: 1 },
    resultTitle: { fontWeight: 'semibold' },
    resultDescription: { color: 'fg.muted', fontSize: 'sm' },
    resultBadge: { flexShrink: 0 },
    status: {
      color: 'fg.muted',
      fontSize: 'sm',
      px: 2,
      py: 6,
      textAlign: 'center',
    },
  },
  variants: {
    active: {
      true: {
        result: {
          bg: 'bg.subtle',
          borderColor: 'border.emphasized',
        },
      },
      false: {},
    },
  },
  defaultVariants: { active: false },
});

export const chakraDocsVersionSelectSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-version-select',
  slots: ['root', 'label', 'select'],
  base: {
    root: {
      alignItems: 'center',
      display: 'inline-flex',
      gap: 2,
      minW: 0,
    },
    label: {
      color: 'fg.muted',
      fontSize: 'xs',
      fontWeight: 'semibold',
      lineHeight: 1,
    },
    select: {
      bg: 'bg',
      borderColor: 'border',
      borderRadius: 'md',
      borderWidth: '1px',
      fontSize: 'sm',
      fontWeight: 'semibold',
      h: 8,
      lineHeight: 1,
      minW: '7.5rem',
      px: 2,
    },
  },
});

export const chakraDocsMarkdownContentSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-markdown-content',
  slots: [
    'root',
    'heading',
    'paragraph',
    'list',
    'listItem',
    'inlineCode',
    'link',
    'quote',
    'codeBlock',
    'image',
    'separator',
    'tableContainer',
    'table',
    'tableHead',
    'tableBody',
    'tableRow',
    'tableHeader',
    'tableCell',
    'taskCheckbox',
  ],
  base: {
    root: { gap: 4, minW: 0, maxW: 'full' },
    paragraph: { color: 'fg.muted', fontSize: 'md' },
    list: {
      color: 'fg.muted',
      ps: 6,
      '&:where(ul)': { listStyleType: 'disc' },
      '&:where(ol)': { listStyleType: 'decimal' },
      '&.contains-task-list': { listStyleType: 'none' },
    },
    listItem: { mt: 1 },
    quote: { '& p + p, & p + ul, & p + ol': { mt: 3 } },
    image: { maxW: 'full', h: 'auto' },
    separator: { borderColor: 'border', borderTopWidth: '1px', w: 'full' },
    tableContainer: {
      minW: 0,
      maxW: 'full',
      w: 'full',
      overflowX: 'auto',
      _focusVisible: {
        outline: '2px solid',
        outlineColor: 'fg',
        outlineOffset: '2px',
      },
    },
    table: { borderCollapse: 'collapse', w: 'full', fontSize: 'sm' },
    tableHead: { bg: 'bg.subtle' },
    tableHeader: {
      borderBottomWidth: '1px',
      borderColor: 'border',
      p: 3,
      fontWeight: 'semibold',
    },
    tableCell: {
      borderBottomWidth: '1px',
      borderColor: 'border',
      p: 3,
      verticalAlign: 'top',
    },
    taskCheckbox: { me: 2, verticalAlign: 'middle' },
    link: {
      color: 'fg',
      fontWeight: 'semibold',
      textDecoration: 'underline',
      textUnderlineOffset: '3px',
    },
  },
  variants: {
    headingLevel: {
      section: { heading: { mt: 8 } },
      subsection: { heading: { mt: 3 } },
    },
  },
  defaultVariants: { headingLevel: 'subsection' },
});

export const chakraDocsPaginationSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-pagination',
  slots: ['root', 'item', 'label', 'link'],
  base: {
    root: {
      borderTopWidth: '1px',
      display: 'flex',
      gap: 4,
      justifyContent: 'space-between',
      mt: 12,
      pt: 6,
    },
    label: { color: 'fg.muted', fontSize: 'sm' },
  },
  variants: {
    direction: {
      previous: {},
      next: { item: { textAlign: 'right' } },
    },
  },
});

export const chakraDocsCalloutSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-callout',
  slots: ['root', 'title', 'content'],
  base: {
    root: { borderWidth: '1px', p: 4, rounded: 'md' },
    title: { fontWeight: 'semibold', mb: 2 },
  },
  variants: {
    status: {
      info: {
        root: {
          bg: 'bg.info',
          borderColor: 'border.info',
          color: 'fg.info',
        },
      },
      warning: {
        root: {
          bg: 'bg.warning',
          borderColor: 'border.warning',
          color: 'fg.warning',
        },
      },
      success: {
        root: {
          bg: 'bg.success',
          borderColor: 'border.success',
          color: 'fg.success',
        },
      },
      danger: {
        root: {
          bg: 'bg.error',
          borderColor: 'border.error',
          color: 'fg.error',
        },
      },
    },
  },
  defaultVariants: { status: 'info' },
});

export const chakraDocsCodeBlockSlotRecipe = defineSlotRecipe({
  className: 'chakra-docs-code-block',
  slots: [
    'root',
    'header',
    'title',
    'control',
    'language',
    'copyTrigger',
    'copyIndicator',
    'content',
    'code',
    'codeText',
  ],
  base: {
    root: {
      '--code-block-highlight-bg': 'colors.bg.emphasized',
      '--code-block-highlight-border': 'colors.border.emphasized',
      '--code-block-highlight-added-bg': 'colors.bg.success',
      '--code-block-highlight-added-border': 'colors.border.success',
      '--code-block-highlight-removed-bg': 'colors.bg.error',
      '--code-block-highlight-removed-border': 'colors.border.error',
      bg: 'bg',
      borderColor: 'border',
      color: 'fg',
      overflow: 'hidden',
    },
    header: {
      alignItems: 'center',
      borderBottomColor: 'border',
      borderBottomWidth: '1px',
      display: 'flex',
      gap: 2,
      justifyContent: 'space-between',
      mb: 0,
    },
    title: {
      color: 'fg.muted',
      flex: 1,
      fontFamily: 'mono',
      minW: 0,
    },
    control: {
      alignItems: 'center',
      display: 'inline-flex',
      flexShrink: 0,
      gap: 2,
    },
    language: {
      color: 'fg.muted',
      fontFamily: 'mono',
      fontSize: 'xs',
    },
    copyTrigger: {
      alignItems: 'center',
      appearance: 'none',
      bg: 'transparent',
      borderRadius: 'sm',
      color: 'fg.muted',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: 'sm',
      minH: 7,
      px: 2,
      _hover: { bg: 'bg.subtle', color: 'fg' },
      _focusVisible: { outline: '2px solid', outlineColor: 'fg' },
    },
    copyIndicator: {
      alignItems: 'center',
      display: 'inline-flex',
    },
    content: { maxW: 'full', overflow: 'hidden' },
    code: {
      fontFamily: 'mono',
      maxW: 'full',
      overflowX: 'auto',
      overflowY: 'hidden',
      whiteSpace: 'pre',
    },
    codeText: { display: 'block', minW: 0 },
  },
  variants: {
    variant: {
      outline: {
        root: { borderColor: 'border', borderWidth: '1px' },
      },
      subtle: {
        root: {
          bg: 'bg.subtle',
          borderColor: 'transparent',
          borderWidth: '1px',
        },
      },
      plain: {
        root: { borderRadius: 0, borderWidth: 0 },
      },
    },
  },
  defaultVariants: { variant: 'outline' },
});

export const chakraDocsSlotRecipes: Record<
  ChakraDocsRecipeKey,
  ChakraDocsSlotRecipeConfig
> = {
  [chakraDocsRecipeKeys.apiTable]: chakraDocsApiTableSlotRecipe,
  [chakraDocsRecipeKeys.article]: chakraDocsArticleSlotRecipe,
  [chakraDocsRecipeKeys.badge]: chakraDocsBadgeSlotRecipe,
  [chakraDocsRecipeKeys.breadcrumbs]: chakraDocsBreadcrumbsSlotRecipe,
  [chakraDocsRecipeKeys.callout]: chakraDocsCalloutSlotRecipe,
  [chakraDocsRecipeKeys.cards]: chakraDocsCardsSlotRecipe,
  [chakraDocsRecipeKeys.codeBlock]: chakraDocsCodeBlockSlotRecipe,
  [chakraDocsRecipeKeys.feedback]: chakraDocsFeedbackSlotRecipe,
  [chakraDocsRecipeKeys.layout]: chakraDocsLayoutSlotRecipe,
  [chakraDocsRecipeKeys.headingPermalink]: chakraDocsHeadingPermalinkSlotRecipe,
  [chakraDocsRecipeKeys.markdownContent]: chakraDocsMarkdownContentSlotRecipe,
  [chakraDocsRecipeKeys.mobileNavigation]: chakraDocsMobileNavigationSlotRecipe,
  [chakraDocsRecipeKeys.mobileTableOfContents]:
    chakraDocsMobileTableOfContentsSlotRecipe,
  [chakraDocsRecipeKeys.pageActions]: chakraDocsPageActionsSlotRecipe,
  [chakraDocsRecipeKeys.pagination]: chakraDocsPaginationSlotRecipe,
  [chakraDocsRecipeKeys.search]: chakraDocsSearchSlotRecipe,
  [chakraDocsRecipeKeys.sidebar]: chakraDocsSidebarSlotRecipe,
  [chakraDocsRecipeKeys.steps]: chakraDocsStepsSlotRecipe,
  [chakraDocsRecipeKeys.tabs]: chakraDocsTabsSlotRecipe,
  [chakraDocsRecipeKeys.tableOfContents]: chakraDocsTableOfContentsSlotRecipe,
  [chakraDocsRecipeKeys.versionSelect]: chakraDocsVersionSelectSlotRecipe,
};

export const chakraDocsThemeConfig: ChakraDocsThemeConfig = defineConfig({
  theme: { slotRecipes: chakraDocsSlotRecipes },
});
